trigger:

* main

variables:
acrName: taskmanager
acrLoginServer: taskmanager.azurecr.io
backendImageName: task-backend
frontendImageName: task-frontend
tag: latest

pool:
vmImage: 'ubuntu-latest'

steps:

# Login to Azure Container Registry

* task: Docker@2
  displayName: Login to ACR
  inputs:
  command: login
  containerRegistry: azure-service-connection

# Build Backend Image

* task: Docker@2
  displayName: Build Backend Image
  inputs:
  command: build
  repository: $(acrLoginServer)/$(backendImageName)
  dockerfile: backend/Dockerfile
  tags: |
  $(tag)

# Push Backend Image

* task: Docker@2
  displayName: Push Backend Image
  inputs:
  command: push
  repository: $(acrLoginServer)/$(backendImageName)
  tags: |
  $(tag)

# Build Frontend Image

* task: Docker@2
  displayName: Build Frontend Image
  inputs:
  command: build
  repository: $(acrLoginServer)/$(frontendImageName)
  dockerfile: frontend/Dockerfile
  tags: |
  $(tag)

# Push Frontend Image

* task: Docker@2
  displayName: Push Frontend Image
  inputs:
  command: push
  repository: $(acrLoginServer)/$(frontendImageName)
  tags: |
  $(tag)
